ANGULAR_SPEED = 'angular-speed'
BUTTONFAN = 'button-fan'
BUTTONGPSREBOOT = 'button-gps-reboot'
BUTTONOPENMODALINFO = 'button-open-modal-info'
BUTTONREMOTECONTROLOK = 'button-remotecontrol-ok'
BUTTONSUNRAYOFF = 'button-sunray-off'
BUTTONSUNRAYREBOOT = 'button-sunray-reboot'
INTERVAL = 'interval'
JOYSTICK = 'joystick'
LINEAR_SPEED = 'linear-speed'
MODALMOWSETTINGS = 'moda-mow-settings'
MODALREMOTECONTROL = 'modal-remotecontrol'
MODALREMOTECONTROLCONTENT = 'modal-remotecontrol-content'
MODALREMOTECONTROLHEADER = 'modal-reomotecontrol-header'
MODALINFO = 'modal-info'
MODALINFOBODY = 'modal-info-body'
NAVBAR = 'navbar'
NAVBARCOLLAPSE = 'navbar-collapse'
NAVBARTOGGLER = 'navbar-toggler'
OFFCANVAS = 'offcanvas'
OPEN_OFFCANVAS = 'open_offcanvas'
VOLTAGECURRENT = 'voltage-current'

#state page
BUTTONCANCEL = 'button-cancel'
BUTTONGO = 'button-go'
BUTTONGOTO = 'button-goto'
BUTTONHOME = 'button-home'
BUTTONMOWALL = 'button-mow-all'
BUTTONMOWSETTINGS = 'button-mow-settings'
BUTTONSTOP = 'button-stop'
BUTTONZONESELECT = 'button-zone-select'
BUTTONGROUPAREAHTML = 'buttongroup-area-html'
BUTTONOKINPUTMAPSETTINGS = 'button-ok-input-map-settings'
DROPDOWNMAPLINETYPE = 'dropdown-maplinetype'
INPUTPATTERNSTATE = 'input-pattern-state'
INPUTMOWOFFSETSTATE = 'input-mowoffset-state'
INPUTMOWOANGLESTATE = 'input-mowangle-state'
STATEMAP = 'state-map'
STATESTRING = 'state-string'

#tasks page
BUTTONGROUPAREA = 'buttongroup-area'
BUTTONCLEARPREVIEW = 'button-clear-preview'
RADIOLINETYPE = 'radio-line-type'
TASKMAP = 'task-map'

#settings page
BUTTONOK = 'button-ok'
BUTTONOKMAPSETTINGS = 'button-ok-mapsettings'
BUTTONOKAPPSETTINGS = 'button-ok-appsettings'
BUTTONSAVEANDREBOOT = 'button-save-and-reboot'
BUTTONSAVEANDREBOOTMAPSETTINGS = 'button-save-and-reboot-mapsettings'
BUTTONSAVEANDREBOOTAPPSETTINGS = 'button-save-and-reboot-appsettings'
IPADRESSROVER = 'ip-adress-rover'
SUNRAYPASS = 'sunray-pass'
RADIOCONNECTIONTYPE = 'radio-connection-type'
MODALCONNECTION = 'modal-connection'
MODALMAPSETTINGS = 'modal-mapsettings'
MODALAPPSETTINGS = 'modal-appsettings'
MQTTCLIENTID = 'mqtt-clientid'
MQTTUSERNAME = 'mqtt-username'
MQTTPASSWORD = 'mqtt-password'
MQTTSERVER = 'mqtt-server'
MQTTPORT = 'mqtt-port'
MQTTROVERNAME = 'mqtt-rovername'
SERPORT = 'ser-port'
BAUDRATE = 'baudrate'
RADIOPOSITIONMODE = 'radio-position-mode'
POSITIONMODELON = 'position-mode-lon'
POSITIONMODELAT = 'position-mode-lat'
MQTTCONNECTIONSTYLE = 'mqtt-connection-style'
HTTPCONNECTIONSTYLE = 'http-connection-style'
UARTCONNECTIONSTYLE = 'uart-connection-style'
POSITIONMODESTYLE = 'position-mode-style'
MOWOFFSETSETTINGS = 'mow-offset-settings'
MOWANGLESETTINGS = 'mow-angle-settings'
MOWEDGESETTINGS = 'mow-edge-settings'
DISTANCETOBORDERSETTINGS = 'distance-to-border-settings'
PATTERNSETTINGS = 'pattern-settings'
MAXAGESETTINGS = 'maxage-settings'
TIMETOOFFLINESETTINGS = 'timetooffline-settins'
VOLTAGEMINSETTINGS = 'voltagemin-settings'
VOLTAGEMAXSETTINGS = 'voltagemax-settings'
CURRENTTHDCHARGESETTINGS = 'currentthdcharge-settings'

#mapping page
BUTTONSAVEIMPORTEDPERIMETER = 'button-save-imported-perimeter'
BUTTONHOMEADD = 'button-home-add'
BUTTONPERIMETERADD = 'button-perimeter-add'
BUTTONPERIMETERDIFF = 'button-perimeter-diff'
BUTTONADDNEWPOINT = 'button-add-new-point'
BUTTONDELETELASTPOINT = 'button-delete-last-point'
BUTTONFINISHFIGURE = 'button-finish-figure'
BUTTONSELECTPERIMETER = 'button-select-perimeter'
BUTTONREMOVEPERIMETER = 'button-remove-perimeter'
BUTTONADDNEWPERIMETER = 'button-add-new-perimeter'
BUTTONCOPYPERIMETER = 'button-copy-perimeter'
DROPDOWNSUNRAYIMPORT = 'dropdown-sunray-import'
DROPDOWNCHOOSEPERIMETER = 'dropdown-choose-perimeter'
OKBUTTONSUNRAYIMPORT = 'ok-button-sunray-import'
OKBUTTONOVERWRITEPERIMTER = 'ok-button-overwrite-perimeter'
OKBUTTONFIGUREFINISHED = 'ok-button-figure-finished'
OKBUTTONSELECTEDPERIMETER = 'ok-button-selected-perimeter'
OKBUTTONNEWPERIMETER = 'ok-button-new-perimeter'
OKBUTTONCOPYPERIMETER = 'ok-button-copy-perimeter'
OKBUTTONREMOVEPERIMETER = 'ok-button-remove-perimeter'
UPLOADSUNRAYFILE = 'upload-sunray-file'
MAPPINGMAP = 'mapping-map'
MODALSUNRAYIMPORT = 'modal-sunray-import'
MODALSUNRAYIMPORTTITLE = 'modal-sunray-import-title'
MODALSUNRAYIMPORTBODY = 'modal-sunray-import-body'
MODALOVERWRITEPERIMETER = 'modal-overwrite-perimter'
MODALFIGUREFINISHED = 'moadal-figure-finished'
MODALSELECTEDPERIMETER = 'modal-selected-perimeter'
MODALADDNEWPERIMETER = 'moadal-add-new-perimeter'
MODALCOPYPERIMETER = 'modal-copy-perimeter'
MODALREMOVEPERIMETER = 'modal-remove-perimeter'
INPUTPERIMETERNAME = 'input-perimeter-name'
INPUTCOPYPERIMETER = 'input-copy-perimeter'

#hidden
MAPPINGHIDDEN = 'mapping-hidden'
SETTINGSHIDDEN = 'settings-hidden'
STATEHIDDEN = 'state-hidden'
STATEHIDDEN2 = 'state-hidden2'
STATEHIDDEN3 = 'state-hidden3'
TASKSHIDDEN = 'tasks-hidden'



